[greeter]
theme-name=WhiteSur-Dark
icon-theme-name=WhiteSur-dark
background=/usr/share/backgrounds/anlight/aurora-blur.png
font-name=Nunito Sans 11
xft-antialias=true
xft-hintstyle=slight
position=50%,center 55%,center
clock-format=%H:%M   ·   %A %d %B
indicators=~host;~spacer;~clock;~spacer;~session;~power
default-user-image=/usr/share/backgrounds/anlight/logo.png
