conky.config = {
    alignment = 'top_right',
    background = true,
    border_width = 0,
    default_color = 'c0caf5',
    color1 = '7aa2f7',
    color2 = '7dcfff',
    cpu_avg_samples = 2,
    double_buffer = true,
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    font = 'Nunito Sans:size=10',
    gap_x = 32,
    gap_y = 56,
    minimum_width = 250,
    no_buffers = true,
    own_window = true,
    own_window_type = 'desktop',
    own_window_argb_visual = true,
    own_window_argb_value = 150,
    own_window_colour = '0a0a14',
    own_window_transparent = false,
    own_window_class = 'Conky',
    update_interval = 1.0,
    use_xft = true,
    xftalpha = 1,
}

conky.text = [[
${font Nunito Sans:bold:size=34}${time %H:%M}${font}
${voffset -8}${color1}${time %A, %d %B}${color}
${voffset 12}${color2}AEGIS RAID CORP.${color}   Anlight OS 0.2
${hr 2}
${voffset 8}${color1}CPU ${color}${cpu}%   ${alignr}${cpubar 7,120}
${color1}RAM ${color}${memperc}%   ${alignr}${membar 7,120}
${color1}DISK${color} ${fs_used_perc /}%   ${alignr}${fsbar 7,120 /}
${voffset 12}${color2}WEATHER${color}
${execi 1800 curl -s 'wttr.in/?format=%C+%t,+%l' 2>/dev/null}
]]
